/*
REST api to TON blockchain explorer

Provide access to indexed TON blockchain

API version: 2.0.0
Contact: support@tonkeeper.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tonapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ImagePreview type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ImagePreview{}

// ImagePreview struct for ImagePreview
type ImagePreview struct {
	Resolution string `json:"resolution"`
	Url string `json:"url"`
}

type _ImagePreview ImagePreview

// NewImagePreview instantiates a new ImagePreview object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewImagePreview(resolution string, url string) *ImagePreview {
	this := ImagePreview{}
	this.Resolution = resolution
	this.Url = url
	return &this
}

// NewImagePreviewWithDefaults instantiates a new ImagePreview object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewImagePreviewWithDefaults() *ImagePreview {
	this := ImagePreview{}
	return &this
}

// GetResolution returns the Resolution field value
func (o *ImagePreview) GetResolution() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Resolution
}

// GetResolutionOk returns a tuple with the Resolution field value
// and a boolean to check if the value has been set.
func (o *ImagePreview) GetResolutionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Resolution, true
}

// SetResolution sets field value
func (o *ImagePreview) SetResolution(v string) {
	o.Resolution = v
}

// GetUrl returns the Url field value
func (o *ImagePreview) GetUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Url
}

// GetUrlOk returns a tuple with the Url field value
// and a boolean to check if the value has been set.
func (o *ImagePreview) GetUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Url, true
}

// SetUrl sets field value
func (o *ImagePreview) SetUrl(v string) {
	o.Url = v
}

func (o ImagePreview) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ImagePreview) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["resolution"] = o.Resolution
	toSerialize["url"] = o.Url
	return toSerialize, nil
}

func (o *ImagePreview) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"resolution",
		"url",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varImagePreview := _ImagePreview{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varImagePreview)

	if err != nil {
		return err
	}

	*o = ImagePreview(varImagePreview)

	return err
}

type NullableImagePreview struct {
	value *ImagePreview
	isSet bool
}

func (v NullableImagePreview) Get() *ImagePreview {
	return v.value
}

func (v *NullableImagePreview) Set(val *ImagePreview) {
	v.value = val
	v.isSet = true
}

func (v NullableImagePreview) IsSet() bool {
	return v.isSet
}

func (v *NullableImagePreview) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableImagePreview(val *ImagePreview) *NullableImagePreview {
	return &NullableImagePreview{value: val, isSet: true}
}

func (v NullableImagePreview) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableImagePreview) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


