/*
REST api to TON blockchain explorer

Provide access to indexed TON blockchain

API version: 2.0.0
Contact: support@tonkeeper.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tonapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the DomainNames type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DomainNames{}

// DomainNames struct for DomainNames
type DomainNames struct {
	Domains []string `json:"domains"`
}

type _DomainNames DomainNames

// NewDomainNames instantiates a new DomainNames object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDomainNames(domains []string) *DomainNames {
	this := DomainNames{}
	this.Domains = domains
	return &this
}

// NewDomainNamesWithDefaults instantiates a new DomainNames object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDomainNamesWithDefaults() *DomainNames {
	this := DomainNames{}
	return &this
}

// GetDomains returns the Domains field value
func (o *DomainNames) GetDomains() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Domains
}

// GetDomainsOk returns a tuple with the Domains field value
// and a boolean to check if the value has been set.
func (o *DomainNames) GetDomainsOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Domains, true
}

// SetDomains sets field value
func (o *DomainNames) SetDomains(v []string) {
	o.Domains = v
}

func (o DomainNames) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DomainNames) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["domains"] = o.Domains
	return toSerialize, nil
}

func (o *DomainNames) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"domains",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDomainNames := _DomainNames{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDomainNames)

	if err != nil {
		return err
	}

	*o = DomainNames(varDomainNames)

	return err
}

type NullableDomainNames struct {
	value *DomainNames
	isSet bool
}

func (v NullableDomainNames) Get() *DomainNames {
	return v.value
}

func (v *NullableDomainNames) Set(val *DomainNames) {
	v.value = val
	v.isSet = true
}

func (v NullableDomainNames) IsSet() bool {
	return v.isSet
}

func (v *NullableDomainNames) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDomainNames(val *DomainNames) *NullableDomainNames {
	return &NullableDomainNames{value: val, isSet: true}
}

func (v NullableDomainNames) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDomainNames) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


