/*
REST api to TON blockchain explorer

Provide access to indexed TON blockchain

API version: 2.0.0
Contact: support@tonkeeper.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tonapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the StatusDefaultResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &StatusDefaultResponse{}

// StatusDefaultResponse struct for StatusDefaultResponse
type StatusDefaultResponse struct {
	Error string `json:"error"`
}

type _StatusDefaultResponse StatusDefaultResponse

// NewStatusDefaultResponse instantiates a new StatusDefaultResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewStatusDefaultResponse(error_ string) *StatusDefaultResponse {
	this := StatusDefaultResponse{}
	this.Error = error_
	return &this
}

// NewStatusDefaultResponseWithDefaults instantiates a new StatusDefaultResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewStatusDefaultResponseWithDefaults() *StatusDefaultResponse {
	this := StatusDefaultResponse{}
	return &this
}

// GetError returns the Error field value
func (o *StatusDefaultResponse) GetError() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Error
}

// GetErrorOk returns a tuple with the Error field value
// and a boolean to check if the value has been set.
func (o *StatusDefaultResponse) GetErrorOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Error, true
}

// SetError sets field value
func (o *StatusDefaultResponse) SetError(v string) {
	o.Error = v
}

func (o StatusDefaultResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o StatusDefaultResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["error"] = o.Error
	return toSerialize, nil
}

func (o *StatusDefaultResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"error",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varStatusDefaultResponse := _StatusDefaultResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varStatusDefaultResponse)

	if err != nil {
		return err
	}

	*o = StatusDefaultResponse(varStatusDefaultResponse)

	return err
}

type NullableStatusDefaultResponse struct {
	value *StatusDefaultResponse
	isSet bool
}

func (v NullableStatusDefaultResponse) Get() *StatusDefaultResponse {
	return v.value
}

func (v *NullableStatusDefaultResponse) Set(val *StatusDefaultResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableStatusDefaultResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableStatusDefaultResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableStatusDefaultResponse(val *StatusDefaultResponse) *NullableStatusDefaultResponse {
	return &NullableStatusDefaultResponse{value: val, isSet: true}
}

func (v NullableStatusDefaultResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableStatusDefaultResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


