/*
REST api to TON blockchain explorer

Provide access to indexed TON blockchain

API version: 2.0.0
Contact: support@tonkeeper.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tonapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the GaslessConfigGasJettonsInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GaslessConfigGasJettonsInner{}

// GaslessConfigGasJettonsInner struct for GaslessConfigGasJettonsInner
type GaslessConfigGasJettonsInner struct {
	MasterId string `json:"master_id"`
}

type _GaslessConfigGasJettonsInner GaslessConfigGasJettonsInner

// NewGaslessConfigGasJettonsInner instantiates a new GaslessConfigGasJettonsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGaslessConfigGasJettonsInner(masterId string) *GaslessConfigGasJettonsInner {
	this := GaslessConfigGasJettonsInner{}
	this.MasterId = masterId
	return &this
}

// NewGaslessConfigGasJettonsInnerWithDefaults instantiates a new GaslessConfigGasJettonsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGaslessConfigGasJettonsInnerWithDefaults() *GaslessConfigGasJettonsInner {
	this := GaslessConfigGasJettonsInner{}
	return &this
}

// GetMasterId returns the MasterId field value
func (o *GaslessConfigGasJettonsInner) GetMasterId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.MasterId
}

// GetMasterIdOk returns a tuple with the MasterId field value
// and a boolean to check if the value has been set.
func (o *GaslessConfigGasJettonsInner) GetMasterIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MasterId, true
}

// SetMasterId sets field value
func (o *GaslessConfigGasJettonsInner) SetMasterId(v string) {
	o.MasterId = v
}

func (o GaslessConfigGasJettonsInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GaslessConfigGasJettonsInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["master_id"] = o.MasterId
	return toSerialize, nil
}

func (o *GaslessConfigGasJettonsInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"master_id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGaslessConfigGasJettonsInner := _GaslessConfigGasJettonsInner{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGaslessConfigGasJettonsInner)

	if err != nil {
		return err
	}

	*o = GaslessConfigGasJettonsInner(varGaslessConfigGasJettonsInner)

	return err
}

type NullableGaslessConfigGasJettonsInner struct {
	value *GaslessConfigGasJettonsInner
	isSet bool
}

func (v NullableGaslessConfigGasJettonsInner) Get() *GaslessConfigGasJettonsInner {
	return v.value
}

func (v *NullableGaslessConfigGasJettonsInner) Set(val *GaslessConfigGasJettonsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableGaslessConfigGasJettonsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableGaslessConfigGasJettonsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGaslessConfigGasJettonsInner(val *GaslessConfigGasJettonsInner) *NullableGaslessConfigGasJettonsInner {
	return &NullableGaslessConfigGasJettonsInner{value: val, isSet: true}
}

func (v NullableGaslessConfigGasJettonsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGaslessConfigGasJettonsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


