/*
REST api to TON blockchain explorer

Provide access to indexed TON blockchain

API version: 2.0.0
Contact: support@tonkeeper.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tonapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the GetRawMasterchainInfoExt200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetRawMasterchainInfoExt200Response{}

// GetRawMasterchainInfoExt200Response struct for GetRawMasterchainInfoExt200Response
type GetRawMasterchainInfoExt200Response struct {
	Mode int32 `json:"mode"`
	Version int32 `json:"version"`
	Capabilities int64 `json:"capabilities"`
	Last BlockRaw `json:"last"`
	LastUtime int32 `json:"last_utime"`
	Now int32 `json:"now"`
	StateRootHash string `json:"state_root_hash"`
	Init InitStateRaw `json:"init"`
}

type _GetRawMasterchainInfoExt200Response GetRawMasterchainInfoExt200Response

// NewGetRawMasterchainInfoExt200Response instantiates a new GetRawMasterchainInfoExt200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetRawMasterchainInfoExt200Response(mode int32, version int32, capabilities int64, last BlockRaw, lastUtime int32, now int32, stateRootHash string, init InitStateRaw) *GetRawMasterchainInfoExt200Response {
	this := GetRawMasterchainInfoExt200Response{}
	this.Mode = mode
	this.Version = version
	this.Capabilities = capabilities
	this.Last = last
	this.LastUtime = lastUtime
	this.Now = now
	this.StateRootHash = stateRootHash
	this.Init = init
	return &this
}

// NewGetRawMasterchainInfoExt200ResponseWithDefaults instantiates a new GetRawMasterchainInfoExt200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetRawMasterchainInfoExt200ResponseWithDefaults() *GetRawMasterchainInfoExt200Response {
	this := GetRawMasterchainInfoExt200Response{}
	return &this
}

// GetMode returns the Mode field value
func (o *GetRawMasterchainInfoExt200Response) GetMode() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Mode
}

// GetModeOk returns a tuple with the Mode field value
// and a boolean to check if the value has been set.
func (o *GetRawMasterchainInfoExt200Response) GetModeOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Mode, true
}

// SetMode sets field value
func (o *GetRawMasterchainInfoExt200Response) SetMode(v int32) {
	o.Mode = v
}

// GetVersion returns the Version field value
func (o *GetRawMasterchainInfoExt200Response) GetVersion() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Version
}

// GetVersionOk returns a tuple with the Version field value
// and a boolean to check if the value has been set.
func (o *GetRawMasterchainInfoExt200Response) GetVersionOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Version, true
}

// SetVersion sets field value
func (o *GetRawMasterchainInfoExt200Response) SetVersion(v int32) {
	o.Version = v
}

// GetCapabilities returns the Capabilities field value
func (o *GetRawMasterchainInfoExt200Response) GetCapabilities() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Capabilities
}

// GetCapabilitiesOk returns a tuple with the Capabilities field value
// and a boolean to check if the value has been set.
func (o *GetRawMasterchainInfoExt200Response) GetCapabilitiesOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Capabilities, true
}

// SetCapabilities sets field value
func (o *GetRawMasterchainInfoExt200Response) SetCapabilities(v int64) {
	o.Capabilities = v
}

// GetLast returns the Last field value
func (o *GetRawMasterchainInfoExt200Response) GetLast() BlockRaw {
	if o == nil {
		var ret BlockRaw
		return ret
	}

	return o.Last
}

// GetLastOk returns a tuple with the Last field value
// and a boolean to check if the value has been set.
func (o *GetRawMasterchainInfoExt200Response) GetLastOk() (*BlockRaw, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Last, true
}

// SetLast sets field value
func (o *GetRawMasterchainInfoExt200Response) SetLast(v BlockRaw) {
	o.Last = v
}

// GetLastUtime returns the LastUtime field value
func (o *GetRawMasterchainInfoExt200Response) GetLastUtime() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.LastUtime
}

// GetLastUtimeOk returns a tuple with the LastUtime field value
// and a boolean to check if the value has been set.
func (o *GetRawMasterchainInfoExt200Response) GetLastUtimeOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.LastUtime, true
}

// SetLastUtime sets field value
func (o *GetRawMasterchainInfoExt200Response) SetLastUtime(v int32) {
	o.LastUtime = v
}

// GetNow returns the Now field value
func (o *GetRawMasterchainInfoExt200Response) GetNow() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Now
}

// GetNowOk returns a tuple with the Now field value
// and a boolean to check if the value has been set.
func (o *GetRawMasterchainInfoExt200Response) GetNowOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Now, true
}

// SetNow sets field value
func (o *GetRawMasterchainInfoExt200Response) SetNow(v int32) {
	o.Now = v
}

// GetStateRootHash returns the StateRootHash field value
func (o *GetRawMasterchainInfoExt200Response) GetStateRootHash() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.StateRootHash
}

// GetStateRootHashOk returns a tuple with the StateRootHash field value
// and a boolean to check if the value has been set.
func (o *GetRawMasterchainInfoExt200Response) GetStateRootHashOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.StateRootHash, true
}

// SetStateRootHash sets field value
func (o *GetRawMasterchainInfoExt200Response) SetStateRootHash(v string) {
	o.StateRootHash = v
}

// GetInit returns the Init field value
func (o *GetRawMasterchainInfoExt200Response) GetInit() InitStateRaw {
	if o == nil {
		var ret InitStateRaw
		return ret
	}

	return o.Init
}

// GetInitOk returns a tuple with the Init field value
// and a boolean to check if the value has been set.
func (o *GetRawMasterchainInfoExt200Response) GetInitOk() (*InitStateRaw, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Init, true
}

// SetInit sets field value
func (o *GetRawMasterchainInfoExt200Response) SetInit(v InitStateRaw) {
	o.Init = v
}

func (o GetRawMasterchainInfoExt200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetRawMasterchainInfoExt200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["mode"] = o.Mode
	toSerialize["version"] = o.Version
	toSerialize["capabilities"] = o.Capabilities
	toSerialize["last"] = o.Last
	toSerialize["last_utime"] = o.LastUtime
	toSerialize["now"] = o.Now
	toSerialize["state_root_hash"] = o.StateRootHash
	toSerialize["init"] = o.Init
	return toSerialize, nil
}

func (o *GetRawMasterchainInfoExt200Response) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"mode",
		"version",
		"capabilities",
		"last",
		"last_utime",
		"now",
		"state_root_hash",
		"init",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGetRawMasterchainInfoExt200Response := _GetRawMasterchainInfoExt200Response{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGetRawMasterchainInfoExt200Response)

	if err != nil {
		return err
	}

	*o = GetRawMasterchainInfoExt200Response(varGetRawMasterchainInfoExt200Response)

	return err
}

type NullableGetRawMasterchainInfoExt200Response struct {
	value *GetRawMasterchainInfoExt200Response
	isSet bool
}

func (v NullableGetRawMasterchainInfoExt200Response) Get() *GetRawMasterchainInfoExt200Response {
	return v.value
}

func (v *NullableGetRawMasterchainInfoExt200Response) Set(val *GetRawMasterchainInfoExt200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableGetRawMasterchainInfoExt200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableGetRawMasterchainInfoExt200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetRawMasterchainInfoExt200Response(val *GetRawMasterchainInfoExt200Response) *NullableGetRawMasterchainInfoExt200Response {
	return &NullableGetRawMasterchainInfoExt200Response{value: val, isSet: true}
}

func (v NullableGetRawMasterchainInfoExt200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetRawMasterchainInfoExt200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


