/*
REST api to TON blockchain explorer

Provide access to indexed TON blockchain

API version: 2.0.0
Contact: support@tonkeeper.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tonapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the GaslessEstimateRequestMessagesInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GaslessEstimateRequestMessagesInner{}

// GaslessEstimateRequestMessagesInner struct for GaslessEstimateRequestMessagesInner
type GaslessEstimateRequestMessagesInner struct {
	Boc string `json:"boc"`
}

type _GaslessEstimateRequestMessagesInner GaslessEstimateRequestMessagesInner

// NewGaslessEstimateRequestMessagesInner instantiates a new GaslessEstimateRequestMessagesInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGaslessEstimateRequestMessagesInner(boc string) *GaslessEstimateRequestMessagesInner {
	this := GaslessEstimateRequestMessagesInner{}
	this.Boc = boc
	return &this
}

// NewGaslessEstimateRequestMessagesInnerWithDefaults instantiates a new GaslessEstimateRequestMessagesInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGaslessEstimateRequestMessagesInnerWithDefaults() *GaslessEstimateRequestMessagesInner {
	this := GaslessEstimateRequestMessagesInner{}
	return &this
}

// GetBoc returns the Boc field value
func (o *GaslessEstimateRequestMessagesInner) GetBoc() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Boc
}

// GetBocOk returns a tuple with the Boc field value
// and a boolean to check if the value has been set.
func (o *GaslessEstimateRequestMessagesInner) GetBocOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Boc, true
}

// SetBoc sets field value
func (o *GaslessEstimateRequestMessagesInner) SetBoc(v string) {
	o.Boc = v
}

func (o GaslessEstimateRequestMessagesInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GaslessEstimateRequestMessagesInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["boc"] = o.Boc
	return toSerialize, nil
}

func (o *GaslessEstimateRequestMessagesInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"boc",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGaslessEstimateRequestMessagesInner := _GaslessEstimateRequestMessagesInner{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGaslessEstimateRequestMessagesInner)

	if err != nil {
		return err
	}

	*o = GaslessEstimateRequestMessagesInner(varGaslessEstimateRequestMessagesInner)

	return err
}

type NullableGaslessEstimateRequestMessagesInner struct {
	value *GaslessEstimateRequestMessagesInner
	isSet bool
}

func (v NullableGaslessEstimateRequestMessagesInner) Get() *GaslessEstimateRequestMessagesInner {
	return v.value
}

func (v *NullableGaslessEstimateRequestMessagesInner) Set(val *GaslessEstimateRequestMessagesInner) {
	v.value = val
	v.isSet = true
}

func (v NullableGaslessEstimateRequestMessagesInner) IsSet() bool {
	return v.isSet
}

func (v *NullableGaslessEstimateRequestMessagesInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGaslessEstimateRequestMessagesInner(val *GaslessEstimateRequestMessagesInner) *NullableGaslessEstimateRequestMessagesInner {
	return &NullableGaslessEstimateRequestMessagesInner{value: val, isSet: true}
}

func (v NullableGaslessEstimateRequestMessagesInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGaslessEstimateRequestMessagesInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


