/*
REST api to TON blockchain explorer

Provide access to indexed TON blockchain

API version: 2.0.0
Contact: support@tonkeeper.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tonapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the GetRawAccountState200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetRawAccountState200Response{}

// GetRawAccountState200Response struct for GetRawAccountState200Response
type GetRawAccountState200Response struct {
	Id BlockRaw `json:"id"`
	Shardblk BlockRaw `json:"shardblk"`
	ShardProof string `json:"shard_proof"`
	Proof string `json:"proof"`
	State string `json:"state"`
}

type _GetRawAccountState200Response GetRawAccountState200Response

// NewGetRawAccountState200Response instantiates a new GetRawAccountState200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetRawAccountState200Response(id BlockRaw, shardblk BlockRaw, shardProof string, proof string, state string) *GetRawAccountState200Response {
	this := GetRawAccountState200Response{}
	this.Id = id
	this.Shardblk = shardblk
	this.ShardProof = shardProof
	this.Proof = proof
	this.State = state
	return &this
}

// NewGetRawAccountState200ResponseWithDefaults instantiates a new GetRawAccountState200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetRawAccountState200ResponseWithDefaults() *GetRawAccountState200Response {
	this := GetRawAccountState200Response{}
	return &this
}

// GetId returns the Id field value
func (o *GetRawAccountState200Response) GetId() BlockRaw {
	if o == nil {
		var ret BlockRaw
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *GetRawAccountState200Response) GetIdOk() (*BlockRaw, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *GetRawAccountState200Response) SetId(v BlockRaw) {
	o.Id = v
}

// GetShardblk returns the Shardblk field value
func (o *GetRawAccountState200Response) GetShardblk() BlockRaw {
	if o == nil {
		var ret BlockRaw
		return ret
	}

	return o.Shardblk
}

// GetShardblkOk returns a tuple with the Shardblk field value
// and a boolean to check if the value has been set.
func (o *GetRawAccountState200Response) GetShardblkOk() (*BlockRaw, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Shardblk, true
}

// SetShardblk sets field value
func (o *GetRawAccountState200Response) SetShardblk(v BlockRaw) {
	o.Shardblk = v
}

// GetShardProof returns the ShardProof field value
func (o *GetRawAccountState200Response) GetShardProof() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ShardProof
}

// GetShardProofOk returns a tuple with the ShardProof field value
// and a boolean to check if the value has been set.
func (o *GetRawAccountState200Response) GetShardProofOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ShardProof, true
}

// SetShardProof sets field value
func (o *GetRawAccountState200Response) SetShardProof(v string) {
	o.ShardProof = v
}

// GetProof returns the Proof field value
func (o *GetRawAccountState200Response) GetProof() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Proof
}

// GetProofOk returns a tuple with the Proof field value
// and a boolean to check if the value has been set.
func (o *GetRawAccountState200Response) GetProofOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Proof, true
}

// SetProof sets field value
func (o *GetRawAccountState200Response) SetProof(v string) {
	o.Proof = v
}

// GetState returns the State field value
func (o *GetRawAccountState200Response) GetState() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.State
}

// GetStateOk returns a tuple with the State field value
// and a boolean to check if the value has been set.
func (o *GetRawAccountState200Response) GetStateOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.State, true
}

// SetState sets field value
func (o *GetRawAccountState200Response) SetState(v string) {
	o.State = v
}

func (o GetRawAccountState200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetRawAccountState200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["shardblk"] = o.Shardblk
	toSerialize["shard_proof"] = o.ShardProof
	toSerialize["proof"] = o.Proof
	toSerialize["state"] = o.State
	return toSerialize, nil
}

func (o *GetRawAccountState200Response) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"shardblk",
		"shard_proof",
		"proof",
		"state",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGetRawAccountState200Response := _GetRawAccountState200Response{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGetRawAccountState200Response)

	if err != nil {
		return err
	}

	*o = GetRawAccountState200Response(varGetRawAccountState200Response)

	return err
}

type NullableGetRawAccountState200Response struct {
	value *GetRawAccountState200Response
	isSet bool
}

func (v NullableGetRawAccountState200Response) Get() *GetRawAccountState200Response {
	return v.value
}

func (v *NullableGetRawAccountState200Response) Set(val *GetRawAccountState200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableGetRawAccountState200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableGetRawAccountState200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetRawAccountState200Response(val *GetRawAccountState200Response) *NullableGetRawAccountState200Response {
	return &NullableGetRawAccountState200Response{value: val, isSet: true}
}

func (v NullableGetRawAccountState200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetRawAccountState200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


