/*
REST api to TON blockchain explorer

Provide access to indexed TON blockchain

API version: 2.0.0
Contact: support@tonkeeper.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tonapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the JettonBalanceLock type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &JettonBalanceLock{}

// JettonBalanceLock struct for JettonBalanceLock
type JettonBalanceLock struct {
	Amount string `json:"amount"`
	Till int64 `json:"till"`
}

type _JettonBalanceLock JettonBalanceLock

// NewJettonBalanceLock instantiates a new JettonBalanceLock object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewJettonBalanceLock(amount string, till int64) *JettonBalanceLock {
	this := JettonBalanceLock{}
	this.Amount = amount
	this.Till = till
	return &this
}

// NewJettonBalanceLockWithDefaults instantiates a new JettonBalanceLock object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewJettonBalanceLockWithDefaults() *JettonBalanceLock {
	this := JettonBalanceLock{}
	return &this
}

// GetAmount returns the Amount field value
func (o *JettonBalanceLock) GetAmount() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Amount
}

// GetAmountOk returns a tuple with the Amount field value
// and a boolean to check if the value has been set.
func (o *JettonBalanceLock) GetAmountOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Amount, true
}

// SetAmount sets field value
func (o *JettonBalanceLock) SetAmount(v string) {
	o.Amount = v
}

// GetTill returns the Till field value
func (o *JettonBalanceLock) GetTill() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Till
}

// GetTillOk returns a tuple with the Till field value
// and a boolean to check if the value has been set.
func (o *JettonBalanceLock) GetTillOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Till, true
}

// SetTill sets field value
func (o *JettonBalanceLock) SetTill(v int64) {
	o.Till = v
}

func (o JettonBalanceLock) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o JettonBalanceLock) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["amount"] = o.Amount
	toSerialize["till"] = o.Till
	return toSerialize, nil
}

func (o *JettonBalanceLock) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"amount",
		"till",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varJettonBalanceLock := _JettonBalanceLock{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varJettonBalanceLock)

	if err != nil {
		return err
	}

	*o = JettonBalanceLock(varJettonBalanceLock)

	return err
}

type NullableJettonBalanceLock struct {
	value *JettonBalanceLock
	isSet bool
}

func (v NullableJettonBalanceLock) Get() *JettonBalanceLock {
	return v.value
}

func (v *NullableJettonBalanceLock) Set(val *JettonBalanceLock) {
	v.value = val
	v.isSet = true
}

func (v NullableJettonBalanceLock) IsSet() bool {
	return v.isSet
}

func (v *NullableJettonBalanceLock) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableJettonBalanceLock(val *JettonBalanceLock) *NullableJettonBalanceLock {
	return &NullableJettonBalanceLock{value: val, isSet: true}
}

func (v NullableJettonBalanceLock) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableJettonBalanceLock) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


