/*
REST api to TON blockchain explorer

Provide access to indexed TON blockchain

API version: 2.0.0
Contact: support@tonkeeper.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tonapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the TraceID type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TraceID{}

// TraceID struct for TraceID
type TraceID struct {
	Id string `json:"id"`
	Utime int64 `json:"utime"`
}

type _TraceID TraceID

// NewTraceID instantiates a new TraceID object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTraceID(id string, utime int64) *TraceID {
	this := TraceID{}
	this.Id = id
	this.Utime = utime
	return &this
}

// NewTraceIDWithDefaults instantiates a new TraceID object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTraceIDWithDefaults() *TraceID {
	this := TraceID{}
	return &this
}

// GetId returns the Id field value
func (o *TraceID) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *TraceID) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *TraceID) SetId(v string) {
	o.Id = v
}

// GetUtime returns the Utime field value
func (o *TraceID) GetUtime() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Utime
}

// GetUtimeOk returns a tuple with the Utime field value
// and a boolean to check if the value has been set.
func (o *TraceID) GetUtimeOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Utime, true
}

// SetUtime sets field value
func (o *TraceID) SetUtime(v int64) {
	o.Utime = v
}

func (o TraceID) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TraceID) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["utime"] = o.Utime
	return toSerialize, nil
}

func (o *TraceID) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"utime",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varTraceID := _TraceID{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varTraceID)

	if err != nil {
		return err
	}

	*o = TraceID(varTraceID)

	return err
}

type NullableTraceID struct {
	value *TraceID
	isSet bool
}

func (v NullableTraceID) Get() *TraceID {
	return v.value
}

func (v *NullableTraceID) Set(val *TraceID) {
	v.value = val
	v.isSet = true
}

func (v NullableTraceID) IsSet() bool {
	return v.isSet
}

func (v *NullableTraceID) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTraceID(val *TraceID) *NullableTraceID {
	return &NullableTraceID{value: val, isSet: true}
}

func (v NullableTraceID) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTraceID) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


