/*
REST api to TON blockchain explorer

Provide access to indexed TON blockchain

API version: 2.0.0
Contact: support@tonkeeper.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tonapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the SendRawMessageRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SendRawMessageRequest{}

// SendRawMessageRequest struct for SendRawMessageRequest
type SendRawMessageRequest struct {
	Body string `json:"body"`
}

type _SendRawMessageRequest SendRawMessageRequest

// NewSendRawMessageRequest instantiates a new SendRawMessageRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSendRawMessageRequest(body string) *SendRawMessageRequest {
	this := SendRawMessageRequest{}
	this.Body = body
	return &this
}

// NewSendRawMessageRequestWithDefaults instantiates a new SendRawMessageRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSendRawMessageRequestWithDefaults() *SendRawMessageRequest {
	this := SendRawMessageRequest{}
	return &this
}

// GetBody returns the Body field value
func (o *SendRawMessageRequest) GetBody() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Body
}

// GetBodyOk returns a tuple with the Body field value
// and a boolean to check if the value has been set.
func (o *SendRawMessageRequest) GetBodyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Body, true
}

// SetBody sets field value
func (o *SendRawMessageRequest) SetBody(v string) {
	o.Body = v
}

func (o SendRawMessageRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SendRawMessageRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["body"] = o.Body
	return toSerialize, nil
}

func (o *SendRawMessageRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"body",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSendRawMessageRequest := _SendRawMessageRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSendRawMessageRequest)

	if err != nil {
		return err
	}

	*o = SendRawMessageRequest(varSendRawMessageRequest)

	return err
}

type NullableSendRawMessageRequest struct {
	value *SendRawMessageRequest
	isSet bool
}

func (v NullableSendRawMessageRequest) Get() *SendRawMessageRequest {
	return v.value
}

func (v *NullableSendRawMessageRequest) Set(val *SendRawMessageRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableSendRawMessageRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableSendRawMessageRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSendRawMessageRequest(val *SendRawMessageRequest) *NullableSendRawMessageRequest {
	return &NullableSendRawMessageRequest{value: val, isSet: true}
}

func (v NullableSendRawMessageRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSendRawMessageRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


