/*
REST api to TON blockchain explorer

Provide access to indexed TON blockchain

API version: 2.0.0
Contact: support@tonkeeper.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tonapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the TonConnectProof200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TonConnectProof200Response{}

// TonConnectProof200Response struct for TonConnectProof200Response
type TonConnectProof200Response struct {
	Token string `json:"token"`
}

type _TonConnectProof200Response TonConnectProof200Response

// NewTonConnectProof200Response instantiates a new TonConnectProof200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTonConnectProof200Response(token string) *TonConnectProof200Response {
	this := TonConnectProof200Response{}
	this.Token = token
	return &this
}

// NewTonConnectProof200ResponseWithDefaults instantiates a new TonConnectProof200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTonConnectProof200ResponseWithDefaults() *TonConnectProof200Response {
	this := TonConnectProof200Response{}
	return &this
}

// GetToken returns the Token field value
func (o *TonConnectProof200Response) GetToken() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Token
}

// GetTokenOk returns a tuple with the Token field value
// and a boolean to check if the value has been set.
func (o *TonConnectProof200Response) GetTokenOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Token, true
}

// SetToken sets field value
func (o *TonConnectProof200Response) SetToken(v string) {
	o.Token = v
}

func (o TonConnectProof200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TonConnectProof200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["token"] = o.Token
	return toSerialize, nil
}

func (o *TonConnectProof200Response) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"token",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varTonConnectProof200Response := _TonConnectProof200Response{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varTonConnectProof200Response)

	if err != nil {
		return err
	}

	*o = TonConnectProof200Response(varTonConnectProof200Response)

	return err
}

type NullableTonConnectProof200Response struct {
	value *TonConnectProof200Response
	isSet bool
}

func (v NullableTonConnectProof200Response) Get() *TonConnectProof200Response {
	return v.value
}

func (v *NullableTonConnectProof200Response) Set(val *TonConnectProof200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableTonConnectProof200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableTonConnectProof200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTonConnectProof200Response(val *TonConnectProof200Response) *NullableTonConnectProof200Response {
	return &NullableTonConnectProof200Response{value: val, isSet: true}
}

func (v NullableTonConnectProof200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTonConnectProof200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


